-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 22:07:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Askhsh1-MovieStar
-- -----------------------------------------------------
-- Prwth askhsh sto mathima sxediasi kai xrisi basewn dedomenwn

-- -----------------------------------------------------
-- Schema Askhsh1-MovieStar
--
-- Prwth askhsh sto mathima sxediasi kai xrisi basewn dedomenwn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Askhsh1-MovieStar` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Askhsh1-MovieStar` ;

-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Player` (
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(90) NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last name` VARCHAR(45) NOT NULL,
  `Birth` DATE NOT NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Game` (
  `GameID` INT NOT NULL AUTO_INCREMENT,
  `Start_Time` DATETIME NOT NULL,
  `Player_Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GameID`),
  INDEX `fk_Games_Players_idx` (`Player_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Games_Players`
    FOREIGN KEY (`Player_Username`)
    REFERENCES `Askhsh1-MovieStar`.`Player` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Director` (
  `Name` VARCHAR(45) NOT NULL,
  `Birth` DATE NOT NULL,
  `Points` INT NOT NULL,
  `GameID` INT NOT NULL,
  PRIMARY KEY (`Name`, `GameID`),
  INDEX `fk_Directors_Games1_idx` (`GameID` ASC) VISIBLE,
  CONSTRAINT `fk_Directors_Games1`
    FOREIGN KEY (`GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Genre` (
  `Genre_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Genre_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Script`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Script` (
  `ScriptID` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `Previous_ScriptID` INT NOT NULL,
  PRIMARY KEY (`ScriptID`),
  INDEX `fk_Script_Script1_idx` (`Previous_ScriptID` ASC) VISIBLE,
  CONSTRAINT `fk_Script_Script1`
    FOREIGN KEY (`Previous_ScriptID`)
    REFERENCES `Askhsh1-MovieStar`.`Script` (`ScriptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Production_Studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Production_Studio` (
  `Name` INT NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Movie` (
  `movieID` INT NOT NULL,
  `Genre_type` VARCHAR(45) NOT NULL,
  `Script_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `duration` FLOAT NOT NULL,
  `year` INT NOT NULL,
  `Production_Studio_Name` INT NOT NULL,
  PRIMARY KEY (`movieID`),
  INDEX `fk_Movies_Genres1_idx` (`Genre_type` ASC) VISIBLE,
  INDEX `fk_Movies_Script1_idx` (`Script_id` ASC) VISIBLE,
  INDEX `fk_Movie_Production_Studio1_idx` (`Production_Studio_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Movies_Genres1`
    FOREIGN KEY (`Genre_type`)
    REFERENCES `Askhsh1-MovieStar`.`Genre` (`Genre_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movies_Script1`
    FOREIGN KEY (`Script_id`)
    REFERENCES `Askhsh1-MovieStar`.`Script` (`ScriptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Production_Studio1`
    FOREIGN KEY (`Production_Studio_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Production_Studio` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Local_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Local_Movie` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `movieID` INT NOT NULL,
  PRIMARY KEY (`movieID`),
  INDEX `fk_Local Movies_Directors1_idx` (`Director_Name` ASC) VISIBLE,
  INDEX `fk_Local Movies_Movies1_idx` (`movieID` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Sponsor` (
  `Name` VARCHAR(45) NOT NULL,
  `Vat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Vat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Actor` (
  `Name` VARCHAR(45) NOT NULL,
  `Birth` DATE NOT NULL,
  `Photo` BLOB NOT NULL,
  PRIMARY KEY (`Name`, `Birth`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Technical_Trait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Technical_Trait` (
  `Kind` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Kind`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Physical_Trait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Physical_Trait` (
  `Kind` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Kind`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Spiritual_Trait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Spiritual_Trait` (
  `Kind` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Kind`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Seminar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Seminar` (
  `Title` VARCHAR(45) NOT NULL,
  `bonus` INT NOT NULL,
  `Technical_Trait_Kind` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title`),
  INDEX `fk_Seminars_Technical Traits1_idx` (`Technical_Trait_Kind` ASC) VISIBLE,
  CONSTRAINT `fk_Seminars_Technical Traits1`
    FOREIGN KEY (`Technical_Trait_Kind`)
    REFERENCES `Askhsh1-MovieStar`.`Technical_Trait` (`Kind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Country` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`City` (
  `Name` VARCHAR(45) NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Country_Name`),
  INDEX `fk_Cities_Countries1_idx` (`Country_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Countries1`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`International_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`International_Movie` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `movieID` INT NOT NULL,
  PRIMARY KEY (`movieID`),
  INDEX `fk_Nationall Movies_Directors1_idx` (`Director_Name` ASC) VISIBLE,
  INDEX `fk_Nationall Movies_Movies1_idx` (`movieID` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Scenery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Scenery` (
  `Road` VARCHAR(45) NOT NULL,
  `Citiy_Name` VARCHAR(45) NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  `Interational_Movie_movieID` INT NULL,
  PRIMARY KEY (`Road`, `Citiy_Name`, `Country_Name`),
  INDEX `fk_Sceneries_Cities1_idx` (`Citiy_Name` ASC, `Country_Name` ASC) VISIBLE,
  INDEX `fk_Sceneries_Nationall Movies1_idx` (`Interational_Movie_movieID` ASC) VISIBLE,
  CONSTRAINT `fk_Sceneries_Cities1`
    FOREIGN KEY (`Citiy_Name` , `Country_Name`)
    REFERENCES `Askhsh1-MovieStar`.`City` (`Name` , `Country_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sceneries_Nationall Movies1`
    FOREIGN KEY (`Interational_Movie_movieID`)
    REFERENCES `Askhsh1-MovieStar`.`International_Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Award` (
  `Name` VARCHAR(45) NOT NULL,
  `Points` INT NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Event` (
  `Name` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Name`, `Date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Social_Network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Social_Network` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Director_Idolizes_Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Director_Idolizes_Director` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_GameID` INT NOT NULL,
  `Idolized_Director` VARCHAR(45) NOT NULL,
  `Idolized_Director_GameID` INT NOT NULL,
  PRIMARY KEY (`Director_Name`, `Director_GameID`, `Idolized_Director`, `Idolized_Director_GameID`),
  INDEX `fk_Directors_has_Directors_Directors2_idx` (`Idolized_Director` ASC, `Idolized_Director_GameID` ASC) VISIBLE,
  INDEX `fk_Directors_has_Directors_Directors1_idx` (`Director_Name` ASC, `Director_GameID` ASC) VISIBLE,
  CONSTRAINT `fk_Directors_has_Directors_Directors1`
    FOREIGN KEY (`Director_Name` , `Director_GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Director` (`Name` , `GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Directors_has_Directors_Directors2`
    FOREIGN KEY (`Idolized_Director` , `Idolized_Director_GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Director` (`Name` , `GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Director_Idolizes_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Director_Idolizes_Movie` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `GameID` INT NOT NULL,
  `Idolizes_movieID` INT NOT NULL,
  PRIMARY KEY (`Director_Name`, `GameID`, `Idolizes_movieID`),
  INDEX `fk_Directors_has_Movies_Movies1_idx` (`Idolizes_movieID` ASC) VISIBLE,
  INDEX `fk_Directors_has_Movies_Directors1_idx` (`Director_Name` ASC, `GameID` ASC) VISIBLE,
  CONSTRAINT `fk_Directors_has_Movies_Directors1`
    FOREIGN KEY (`Director_Name` , `GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Director` (`Name` , `GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Directors_has_Movies_Movies1`
    FOREIGN KEY (`Idolizes_movieID`)
    REFERENCES `Askhsh1-MovieStar`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Role` (
  `Role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Role_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Movie_has_Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Movie_has_Actor` (
  `Movie_movieID` INT NOT NULL,
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Birth` DATE NOT NULL,
  `Role_name` VARCHAR(45) NOT NULL,
  `Start_date` DATE NOT NULL,
  `Exp_date` DATE NOT NULL,
  `Salary` FLOAT NOT NULL,
  PRIMARY KEY (`Movie_movieID`, `Actor_Name`, `Actor_Birth`),
  INDEX `fk_Movies_has_Actors_Actors1_idx` (`Actor_Name` ASC, `Actor_Birth` ASC) VISIBLE,
  INDEX `fk_Movies_has_Actors_Movies1_idx` (`Movie_movieID` ASC) VISIBLE,
  INDEX `fk_Movies_has_Actors_Roles1_idx` (`Role_name` ASC) VISIBLE,
  CONSTRAINT `fk_Movies_has_Actors_Movies1`
    FOREIGN KEY (`Movie_movieID`)
    REFERENCES `Askhsh1-MovieStar`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movies_has_Actors_Actors1`
    FOREIGN KEY (`Actor_Name` , `Actor_Birth`)
    REFERENCES `Askhsh1-MovieStar`.`Actor` (`Name` , `Birth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movies_has_Actors_Roles1`
    FOREIGN KEY (`Role_name`)
    REFERENCES `Askhsh1-MovieStar`.`Role` (`Role_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Actor_has_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Actor_has_Country` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Birth` DATE NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Birth`, `Country_Name`),
  INDEX `fk_Actors_has_Countries_Countries1_idx` (`Country_Name` ASC) VISIBLE,
  INDEX `fk_Actors_has_Countries_Actors1_idx` (`Actor_Name` ASC, `Actor_Birth` ASC) VISIBLE,
  CONSTRAINT `fk_Actors_has_Countries_Actors1`
    FOREIGN KEY (`Actor_Name` , `Actor_Birth`)
    REFERENCES `Askhsh1-MovieStar`.`Actor` (`Name` , `Birth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_has_Countries_Countries1`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Actor_has_Technical_Trait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Actor_has_Technical_Trait` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Birth` DATE NOT NULL,
  `Technical_Trait_Kind` VARCHAR(45) NOT NULL,
  `grade` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Birth`, `Technical_Trait_Kind`),
  INDEX `fk_Actors_has_Technical Traits_Technical Traits1_idx` (`Technical_Trait_Kind` ASC) VISIBLE,
  INDEX `fk_Actors_has_Technical Traits_Actors1_idx` (`Actor_Name` ASC, `Actor_Birth` ASC) VISIBLE,
  CONSTRAINT `fk_Actors_has_Technical Traits_Actors1`
    FOREIGN KEY (`Actor_Name` , `Actor_Birth`)
    REFERENCES `Askhsh1-MovieStar`.`Actor` (`Name` , `Birth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_has_Technical Traits_Technical Traits1`
    FOREIGN KEY (`Technical_Trait_Kind`)
    REFERENCES `Askhsh1-MovieStar`.`Technical_Trait` (`Kind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Actor_has_Physical_Trait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Actor_has_Physical_Trait` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Birth` DATE NOT NULL,
  `Physical_Trait_Kind` VARCHAR(45) NOT NULL,
  `grade` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Birth`, `Physical_Trait_Kind`),
  INDEX `fk_Actors_has_Physical Traits_Physical Traits1_idx` (`Physical_Trait_Kind` ASC) VISIBLE,
  INDEX `fk_Actors_has_Physical Traits_Actors1_idx` (`Actor_Name` ASC, `Actor_Birth` ASC) VISIBLE,
  CONSTRAINT `fk_Actors_has_Physical Traits_Actors1`
    FOREIGN KEY (`Actor_Name` , `Actor_Birth`)
    REFERENCES `Askhsh1-MovieStar`.`Actor` (`Name` , `Birth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_has_Physical Traits_Physical Traits1`
    FOREIGN KEY (`Physical_Trait_Kind`)
    REFERENCES `Askhsh1-MovieStar`.`Physical_Trait` (`Kind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Actor_has_Spiritual_Trait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Actor_has_Spiritual_Trait` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Birth` DATE NOT NULL,
  `Spiritual_Trait_Kind` VARCHAR(45) NOT NULL,
  `grade` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Birth`, `Spiritual_Trait_Kind`),
  INDEX `fk_Actors_has_Spiritual Traits_Spiritual Traits1_idx` (`Spiritual_Trait_Kind` ASC) VISIBLE,
  INDEX `fk_Actors_has_Spiritual Traits_Actors1_idx` (`Actor_Name` ASC, `Actor_Birth` ASC) VISIBLE,
  CONSTRAINT `fk_Actors_has_Spiritual Traits_Actors1`
    FOREIGN KEY (`Actor_Name` , `Actor_Birth`)
    REFERENCES `Askhsh1-MovieStar`.`Actor` (`Name` , `Birth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_has_Spiritual Traits_Spiritual Traits1`
    FOREIGN KEY (`Spiritual_Trait_Kind`)
    REFERENCES `Askhsh1-MovieStar`.`Spiritual_Trait` (`Kind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Actor_has_Seminar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Actor_has_Seminar` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Birth` DATE NOT NULL,
  `Seminar_Title` VARCHAR(45) NOT NULL,
  `GameID` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Birth`, `Seminar_Title`, `GameID`),
  INDEX `fk_Actors_has_Seminars_Seminars1_idx` (`Seminar_Title` ASC) VISIBLE,
  INDEX `fk_Actors_has_Seminars_Actors1_idx` (`Actor_Name` ASC, `Actor_Birth` ASC) VISIBLE,
  INDEX `fk_Actor_has_Seminar_Game1_idx` (`GameID` ASC) VISIBLE,
  CONSTRAINT `fk_Actors_has_Seminars_Actors1`
    FOREIGN KEY (`Actor_Name` , `Actor_Birth`)
    REFERENCES `Askhsh1-MovieStar`.`Actor` (`Name` , `Birth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_has_Seminars_Seminars1`
    FOREIGN KEY (`Seminar_Title`)
    REFERENCES `Askhsh1-MovieStar`.`Seminar` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Seminar_Game1`
    FOREIGN KEY (`GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Event_has_Social_Network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Event_has_Social_Network` (
  `Event_Name` VARCHAR(45) NOT NULL,
  `Event_Date` DATE NOT NULL,
  `Social_Network_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Event_Name`, `Event_Date`, `Social_Network_Name`),
  INDEX `fk_Events_has_Social Networks_Social Networks1_idx` (`Social_Network_Name` ASC) VISIBLE,
  INDEX `fk_Events_has_Social Networks_Events1_idx` (`Event_Name` ASC, `Event_Date` ASC) VISIBLE,
  CONSTRAINT `fk_Events_has_Social Networks_Events1`
    FOREIGN KEY (`Event_Name` , `Event_Date`)
    REFERENCES `Askhsh1-MovieStar`.`Event` (`Name` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Social Networks_Social Networks1`
    FOREIGN KEY (`Social_Network_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Social_Network` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Director_is_friend_with_at_SN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Director_is_friend_with_at_SN` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_GameID` INT NOT NULL,
  `Social_Network_Name` VARCHAR(45) NOT NULL,
  `Friend_Name` VARCHAR(45) NOT NULL,
  `Friend_GameID` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  PRIMARY KEY (`Director_Name`, `Director_GameID`, `Social_Network_Name`, `Friend_Name`, `Friend_GameID`),
  INDEX `fk_Directors_has_Social Networks_Social Networks1_idx` (`Social_Network_Name` ASC) VISIBLE,
  INDEX `fk_Directors_has_Social Networks_Directors1_idx` (`Director_Name` ASC, `Director_GameID` ASC) VISIBLE,
  INDEX `fk_Director_is_friend_with_at_SN_Directors1_idx` (`Friend_Name` ASC, `Friend_GameID` ASC) VISIBLE,
  CONSTRAINT `fk_Directors_has_Social Networks_Directors1`
    FOREIGN KEY (`Director_Name` , `Director_GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Director` (`Name` , `GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Directors_has_Social Networks_Social Networks1`
    FOREIGN KEY (`Social_Network_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Social_Network` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_is_friend_with_at_SN_Directors1`
    FOREIGN KEY (`Friend_Name` , `Friend_GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Director` (`Name` , `GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Movie_Participates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Movie_Participates` (
  `Event_Name` VARCHAR(45) NOT NULL,
  `Event_Date` DATE NOT NULL,
  `Award_Name` VARCHAR(45) NOT NULL,
  `movieID` INT NOT NULL,
  PRIMARY KEY (`Event_Name`, `Event_Date`, `Award_Name`, `movieID`),
  INDEX `fk_Events_has_Awards_Awards1_idx` (`Award_Name` ASC) VISIBLE,
  INDEX `fk_Events_has_Awards_Events1_idx` (`Event_Name` ASC, `Event_Date` ASC) VISIBLE,
  INDEX `fk_Events_has_Awards_Movies1_idx` (`movieID` ASC) VISIBLE,
  CONSTRAINT `fk_Events_has_Awards_Events1`
    FOREIGN KEY (`Event_Name` , `Event_Date`)
    REFERENCES `Askhsh1-MovieStar`.`Event` (`Name` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Awards_Awards1`
    FOREIGN KEY (`Award_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Award` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Awards_Movies1`
    FOREIGN KEY (`movieID`)
    REFERENCES `Askhsh1-MovieStar`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Event_has_Award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Event_has_Award` (
  `Event_Name` VARCHAR(45) NOT NULL,
  `Event_Date` DATE NOT NULL,
  `Award_Name` VARCHAR(45) NOT NULL,
  `Winner_movieID` INT NOT NULL,
  PRIMARY KEY (`Event_Name`, `Event_Date`, `Award_Name`),
  INDEX `fk_Events_has_Awards1_Awards1_idx` (`Award_Name` ASC) VISIBLE,
  INDEX `fk_Events_has_Awards1_Events1_idx` (`Event_Name` ASC, `Event_Date` ASC) VISIBLE,
  INDEX `fk_Events_has_Awards1_Movies1_idx` (`Winner_movieID` ASC) VISIBLE,
  CONSTRAINT `fk_Events_has_Awards1_Events1`
    FOREIGN KEY (`Event_Name` , `Event_Date`)
    REFERENCES `Askhsh1-MovieStar`.`Event` (`Name` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Awards1_Awards1`
    FOREIGN KEY (`Award_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Award` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Awards1_Movies1`
    FOREIGN KEY (`Winner_movieID`)
    REFERENCES `Askhsh1-MovieStar`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Local Movie_has_Sceneries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Local Movie_has_Sceneries` (
  `movieID` INT NOT NULL,
  `Scenery_Road` VARCHAR(45) NOT NULL,
  `Scenery_City_Name` VARCHAR(45) NOT NULL,
  `Scenery_Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`movieID`, `Scenery_Road`, `Scenery_City_Name`, `Scenery_Country_Name`),
  INDEX `fk_Local Movies_has_Sceneries_Sceneries1_idx` (`Scenery_Road` ASC, `Scenery_City_Name` ASC, `Scenery_Country_Name` ASC) VISIBLE,
  INDEX `fk_Local Movies_has_Sceneries_Local Movies1_idx` (`movieID` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Sponsor_has_Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Sponsor_has_Movies` (
  `Sponsor_Vat` VARCHAR(45) NOT NULL,
  `MovieID` INT NOT NULL,
  `Sponsorship` FLOAT NOT NULL,
  PRIMARY KEY (`Sponsor_Vat`, `MovieID`),
  INDEX `fk_Sponsor_has_Movies_Movies1_idx` (`MovieID` ASC) VISIBLE,
  INDEX `fk_Sponsor_has_Movies_Sponsor1_idx` (`Sponsor_Vat` ASC) VISIBLE,
  CONSTRAINT `fk_Sponsor_has_Movies_Sponsor1`
    FOREIGN KEY (`Sponsor_Vat`)
    REFERENCES `Askhsh1-MovieStar`.`Sponsor` (`Vat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sponsor_has_Movies_Movies1`
    FOREIGN KEY (`MovieID`)
    REFERENCES `Askhsh1-MovieStar`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Event_has_Social_Network_has_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Event_has_Social_Network_has_Movie` (
  `Event_Name` VARCHAR(45) NOT NULL,
  `Event_Date` DATE NOT NULL,
  `Social_Network_Name` VARCHAR(45) NOT NULL,
  `movieID` INT NOT NULL,
  `Likes` INT NOT NULL,
  PRIMARY KEY (`Event_Name`, `Event_Date`, `Social_Network_Name`, `movieID`),
  INDEX `fk_Events_has_Social Networks_has_Movies_Movies1_idx` (`movieID` ASC) VISIBLE,
  INDEX `fk_Events_has_Social Networks_has_Movies_Events_has_Social _idx` (`Event_Name` ASC, `Event_Date` ASC, `Social_Network_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Events_has_Social Networks_has_Movies_Events_has_Social Ne1`
    FOREIGN KEY (`Event_Name` , `Event_Date` , `Social_Network_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Event_has_Social_Network` (`Event_Name` , `Event_Date` , `Social_Network_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Social Networks_has_Movies_Movies1`
    FOREIGN KEY (`movieID`)
    REFERENCES `Askhsh1-MovieStar`.`Movie` (`movieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Askhsh1-MovieStar`.`Director_has_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Askhsh1-MovieStar`.`Director_has_Country` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_GameID` INT NOT NULL,
  `Country_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Director_Name`, `Director_GameID`, `Country_Name`),
  INDEX `fk_Director_has_Country_Country1_idx` (`Country_Name` ASC) VISIBLE,
  INDEX `fk_Director_has_Country_Director1_idx` (`Director_Name` ASC, `Director_GameID` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Country_Director1`
    FOREIGN KEY (`Director_Name` , `Director_GameID`)
    REFERENCES `Askhsh1-MovieStar`.`Director` (`Name` , `GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Country_Country1`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `Askhsh1-MovieStar`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
